name: Build Padavan

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: [K2P, NEWIFI3, MI-MINI]  # 修改为你的路由器型号
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev unzip gawk python3

    - name: Build Firmware
      run: |
        cd $GITHUB_WORKSPACE/trunk
        ./clear_tree
        cp configs/templates/${{ matrix.device }}.config .config
        sudo ./build.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.device }}-firmware
        path: $GITHUB_WORKSPACE/trunk/images/*.trx
